### ISSUE TITLE
Author, when can you release this MOD?

### ISSUE THREAD

**Issue by mengzhu3261** [Sauleteh/Minecraft-Bot-Mod#2]
Author, when can you release this MOD?

**Comment by Sauleteh** [comment]
Hi, the mod still in progress. It needs a menu but I'm new making this type of mods so it will take a while to release it.

**Comment by mengzhu3261** [comment]
> 嗨，mod 仍在进行中。它需要一个菜单，但我是制作此类模组的新手，因此需要一段时间才能发布它。

Author, how much have you done and what features do you expect to have

**Comment by Sauleteh** [comment]
I already have the player movement, mouse movement and mouse left/right click to break or place blocks. I just need to add a menu to configure the actions you want to have when you activate the bot. There is also a loop function to repeat the actions endlessly.

I don't think I'll add many more actions but I'd also like to add menu automatization too: click on an NPC and select the right slots to do things, but I couldn't figure out how to do that.

**Comment by mengzhu3261** [comment]
Can you test if it bypasses the hyp server?

**Comment by Sauleteh** [comment]
yes, it bypasses Hypixel and all servers, it's client-side, just be aware that someone can report you if you make strange movements

**Comment by mengzhu3261** [comment]
> 是的，它绕过了 Hypixel 和所有服务器，它是客户端的，请注意，如果您做出奇怪的动作，有人可以举报您

Can you write a mode that can be used in bedwars? After opening, you can hang up in bedwars to get experience and coins?
